
package com.informatica.wsh.exception;

import com.informatica.wsh.type.FaultDetails;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WSHFaultDetails", targetNamespace = "http://www.informatica.com/wsh")
public class Fault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetails faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Fault(String message, FaultDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Fault(String message, FaultDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.informatica.wsh.type.FaultDetails
     */
    public FaultDetails getFaultInfo() {
        return faultInfo;
    }

}
