
package com.informatica.wsh.intf;

import com.informatica.wsh.*;
import com.informatica.wsh.enums.EPingState;
import com.informatica.wsh.exception.Fault;
import com.informatica.wsh.type.*;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataIntegrationInterface", targetNamespace = "http://www.informatica.com/wsh")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataIntegrationInterface {


    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns java.lang.String
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "LoginReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public String login(
        @WebParam(name = "Login", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
                LoginRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, mode = WebParam.Mode.OUT, partName = "Context")
        Holder<SessionHeader> context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "LogoutReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public VoidResponse logout(
        @WebParam(name = "Logout", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        VoidRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "InitializeDIServerConnectionReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public VoidResponse initializeDIServerConnection(
        @WebParam(name = "InitializeDIServerConnection", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        InitializeDIServerConnectionRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "DeinitializeDIServerConnectionReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public VoidResponse deinitializeDIServerConnection(
        @WebParam(name = "DeinitializeDIServerConnection", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        VoidRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns int
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartWorkflowLogFetchReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public int startWorkflowLogFetch(
        @WebParam(name = "StartWorkflowLogFetch", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        StartWorkflowLogFetchRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns int
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartSessionLogFetchReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public int startSessionLogFetch(
        @WebParam(name = "StartSessionLogFetch", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        StartSessionLogFetchRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param param
     * @param context
     * @return
     *     returns com.informatica.wsh.type.LogSegment
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetNextLogSegmentReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
    public LogSegment getNextLogSegment(
        @WebParam(name = "GetNextLogSegment", targetNamespace = "http://www.informatica.com/wsh", partName = "param")
        GetNextLogSegmentRequest param,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param pingDIServer
     * @param context
     * @return
     *     returns com.informatica.wsh.enums.EPingState
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "PingDIServerReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "PingDIServerReturn")
    public EPingState pingDIServer(
        @WebParam(name = "PingDIServer", targetNamespace = "http://www.informatica.com/wsh", partName = "PingDIServer")
        PingDIServerRequest pingDIServer,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getDIServerProperties
     * @return
     *     returns com.informatica.wsh.type.DIServerProperties
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetDIServerPropertiesReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetDIServerPropertiesReturn")
    public DIServerProperties getDIServerProperties(
        @WebParam(name = "GetDIServerProperties", targetNamespace = "http://www.informatica.com/wsh", partName = "GetDIServerProperties")
        DIServiceInfo getDIServerProperties,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param startWorkflow
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflowReturn")
    public VoidResponse startWorkflow(
        @WebParam(name = "StartWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflow")
        WorkflowRequest startWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param startWorkflowEx
     * @return
     *     returns com.informatica.wsh.type.TypeStartWorkflowExResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartWorkflowExReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflowExReturn")
    public TypeStartWorkflowExResponse startWorkflowEx(
        @WebParam(name = "StartWorkflowEx", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflowEx")
        TypeStartWorkflowExRequest startWorkflowEx,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param startWorkflowFromTask
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartWorkflowFromTaskReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflowFromTaskReturn")
    public VoidResponse startWorkflowFromTask(
        @WebParam(name = "StartWorkflowFromTask", targetNamespace = "http://www.informatica.com/wsh", partName = "StartWorkflowFromTask")
        WorkflowRequest startWorkflowFromTask,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param stopWorkflow
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StopWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StopWorkflowReturn")
    public VoidResponse stopWorkflow(
        @WebParam(name = "StopWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "StopWorkflow")
        WorkflowRequest stopWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param scheduleWorkflow
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "ScheduleWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "ScheduleWorkflowReturn")
    public VoidResponse scheduleWorkflow(
        @WebParam(name = "ScheduleWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "ScheduleWorkflow")
        WorkflowRequest scheduleWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param unscheduleWorkflow
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "UnscheduleWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "UnscheduleWorkflowReturn")
    public VoidResponse unscheduleWorkflow(
        @WebParam(name = "UnscheduleWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "UnscheduleWorkflow")
        WorkflowRequest unscheduleWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param waitTillWorkflowComplete
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "WaitTillWorkflowCompleteReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "WaitTillWorkflowCompleteReturn")
    public VoidResponse waitTillWorkflowComplete(
        @WebParam(name = "WaitTillWorkflowComplete", targetNamespace = "http://www.informatica.com/wsh", partName = "WaitTillWorkflowComplete")
        WorkflowRequest waitTillWorkflowComplete,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param resumeWorkflow
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "ResumeWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "ResumeWorkflowReturn")
    public VoidResponse resumeWorkflow(
        @WebParam(name = "ResumeWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "ResumeWorkflow")
        WorkflowRequest resumeWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param startTask
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StartTaskReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StartTaskReturn")
    public VoidResponse startTask(
        @WebParam(name = "StartTask", targetNamespace = "http://www.informatica.com/wsh", partName = "StartTask")
        TaskRequest startTask,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param stopTask
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "StopTaskReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "StopTaskReturn")
    public VoidResponse stopTask(
        @WebParam(name = "StopTask", targetNamespace = "http://www.informatica.com/wsh", partName = "StopTask")
        TaskRequest stopTask,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param waitTillTaskComplete
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "WaitTillTaskCompleteReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "WaitTillTaskCompleteReturn")
    public VoidResponse waitTillTaskComplete(
        @WebParam(name = "WaitTillTaskComplete", targetNamespace = "http://www.informatica.com/wsh", partName = "WaitTillTaskComplete")
        TaskRequest waitTillTaskComplete,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param recoverWorkflow
     * @param context
     * @return
     *     returns com.informatica.wsh.type.VoidResponse
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "RecoverWorkflowReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "RecoverWorkflowReturn")
    public VoidResponse recoverWorkflow(
        @WebParam(name = "RecoverWorkflow", targetNamespace = "http://www.informatica.com/wsh", partName = "RecoverWorkflow")
        WorkflowRequest recoverWorkflow,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param monitorDIServer
     * @param context
     * @return
     *     returns com.informatica.wsh.type.DIServerDetails
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "MonitorDIServerReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "MonitorDIServerReturn")
    public DIServerDetails monitorDIServer(
        @WebParam(name = "MonitorDIServer", targetNamespace = "http://www.informatica.com/wsh", partName = "MonitorDIServer")
        MonitorDIServerRequest monitorDIServer,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param getWorkflowDetails
     * @param context
     * @return
     *     returns com.informatica.wsh.type.WorkflowDetails
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetWorkflowDetailsReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowDetailsReturn")
    public WorkflowDetails getWorkflowDetails(
        @WebParam(name = "GetWorkflowDetails", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowDetails")
        WorkflowRequest getWorkflowDetails,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getWorkflowDetailsEx
     * @return
     *     returns com.informatica.wsh.type.DIServerDetails
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetWorkflowDetailsExReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowDetailsExReturn")
    public DIServerDetails getWorkflowDetailsEx(
        @WebParam(name = "GetWorkflowDetailsEx", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowDetailsEx")
        TypeGetWorkflowDetailsExRequest getWorkflowDetailsEx,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getTaskDetails
     * @return
     *     returns com.informatica.wsh.type.TaskDetails
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetTaskDetailsReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetTaskDetailsReturn")
    public TaskDetails getTaskDetails(
        @WebParam(name = "GetTaskDetails", targetNamespace = "http://www.informatica.com/wsh", partName = "GetTaskDetails")
        TaskRequest getTaskDetails,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getTaskDetailsEx
     * @return
     *     returns com.informatica.wsh.type.DIServerDetails
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetTaskDetailsExReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetTaskDetailsExReturn")
    public DIServerDetails getTaskDetailsEx(
        @WebParam(name = "GetTaskDetailsEx", targetNamespace = "http://www.informatica.com/wsh", partName = "GetTaskDetailsEx")
        TypeGetTaskDetailsExRequest getTaskDetailsEx,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getSessionStatistics
     * @return
     *     returns com.informatica.wsh.type.SessionStatistics
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetSessionStatisticsReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessionStatisticsReturn")
    public SessionStatistics getSessionStatistics(
        @WebParam(name = "GetSessionStatistics", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessionStatistics")
                GetSessionStatisticsRequest getSessionStatistics,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getSessionPerformanceData
     * @return
     *     returns com.informatica.wsh.type.SessionPerformanceData
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetSessionPerformanceDataReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessionPerformanceDataReturn")
    public SessionPerformanceData getSessionPerformanceData(
        @WebParam(name = "GetSessionPerformanceData", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessionPerformanceData")
                GetSessionPerformanceDataRequest getSessionPerformanceData,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param getWorkflowLog
     * @param context
     * @return
     *     returns com.informatica.wsh.type.Log
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetWorkflowLogReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowLogReturn")
    public Log getWorkflowLog(
        @WebParam(name = "GetWorkflowLog", targetNamespace = "http://www.informatica.com/wsh", partName = "GetWorkflowLog")
                GetWorkflowLogRequest getWorkflowLog,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

    /**
     * 
     * @param context
     * @param getSessionLog
     * @return
     *     returns com.informatica.wsh.type.Log
     * @throws Fault
     */
    @WebMethod
    @WebResult(name = "GetSessionLogReturn", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessoinLogReturn")
    public Log getSessionLog(
        @WebParam(name = "GetSessionLog", targetNamespace = "http://www.informatica.com/wsh", partName = "GetSessionLog")
        GetSessionLogRequest getSessionLog,
        @WebParam(name = "Context", targetNamespace = "http://www.informatica.com/wsh", header = true, partName = "Context")
        SessionHeader context)
        throws Fault
    ;

}
