
package com.informatica.wsh.port;

import com.informatica.wsh.intf.DataIntegrationInterface;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
public class DataIntegrationService extends Service {

    private static final QName DATAINTEGRATIONSERVICE_QNAME = new QName("http://www.informatica.com/wsh", "DataIntegrationService");

    public DataIntegrationService(URL wsdlDocLocation) {
        super(wsdlDocLocation, DATAINTEGRATIONSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns DataIntegrationInterface
     */
    public DataIntegrationInterface getDataIntegration() {
        return super.getPort(new QName("http://www.informatica.com/wsh", "DataIntegration"), DataIntegrationInterface.class);
    }

}
