
package com.informatica.wsh.port;

import com.informatica.wsh.WshConstants;
import com.informatica.wsh.intf.DataIntegrationInterface;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataIntegrationService", targetNamespace = "http://www.informatica.com/wsh", wsdlLocation = "http://congos:7333/wsh/services/BatchServices/DataIntegration?WSDL")
public class DataIntegrationService extends Service implements WshConstants {

    private final static QName DATAINTEGRATIONSERVICE_QNAME = new QName("http://www.informatica.com/wsh", "DataIntegrationService");

    public DataIntegrationService(URL wsdlDocLocation) {
        super(wsdlDocLocation, DATAINTEGRATIONSERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns DataIntegrationInterface
     */
    @WebEndpoint(name = "DataIntegration")
    public DataIntegrationInterface getDataIntegration() {
        return super.getPort(new QName("http://www.informatica.com/wsh", "DataIntegration"), DataIntegrationInterface.class);
    }

}
