
package com.informatica.wsh.port;

import com.informatica.wsh.WshConstants;
import com.informatica.wsh.intf.MetadataInterface;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MetadataService", targetNamespace = "http://www.informatica.com/wsh", wsdlLocation = "http://congos:7333/wsh/services/BatchServices/Metadata?WSDL")
public class MetadataService extends Service implements WshConstants {

    private final static QName METADATASERVICE_QNAME = new QName("http://www.informatica.com/wsh", "MetadataService");

    public MetadataService(URL wsdlDocLocation) {
        super(wsdlDocLocation, METADATASERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns MetadataInterface
     */
    @WebEndpoint(name = "Metadata")
    public MetadataInterface getMetadata() {
        return super.getPort(new QName("http://www.informatica.com/wsh", "Metadata"), MetadataInterface.class);
    }

}
