
package com.informatica.wsh.port;

import com.informatica.wsh.intf.MetadataInterface;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
public class MetadataService {

    private final Service metadataService;
    private static final QName METADATASERVICE_QNAME = new QName("http://www.informatica.com/wsh", "MetadataService");

    public MetadataService(URL wsdlDocLocation) {
        metadataService = Service.create(wsdlDocLocation, METADATASERVICE_QNAME);
    }

    /**
     * 
     * @return
     *     returns MetadataInterface
     */
    public MetadataInterface getMetadata() {
        return metadataService.getPort(new QName("http://www.informatica.com/wsh", "Metadata"), MetadataInterface.class);
    }

}
